elkarforti/elkarforti/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
#    path('groupaccess/', include('groupaccess.urls')),
    path('admin/', admin.site.urls),
    path('', include('groupaccess.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

elkarforti/groupaccess/urls.py
from django.urls import path

from . import views
from  groupaccess.views import FortiGroupList, FortiGroupCreate, FortiGroupDelete, FortiGroupUpdate

app_name = 'groupaccess'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('groups/<int:pk>/', FortiGroupUpdate.as_view(), name='fortigroup_update'),
    path('groups/', FortiGroupList.as_view()),
]

elkarforti/groupaccess/models.py
from django.db import models
from django.forms import ModelForm
from django.urls import reverse

import pyfortiapi
from Crypto.Cipher import AES # https://nitratine.net/blog/post/python-encryption-and-decryption-with-pycryptodome/
from Crypto.Random import get_random_bytes
from django.core.exceptions import ValidationError

import os.path
from os import path

# Create your models here.

from django.db import models


class FortiParameters(models.Model):
    fortiIP = models.CharField(max_length=16)
    fortiPort = models.IntegerField(default=443)
    fortiVdom = models.CharField(max_length=32)
    fortiUserName = models.CharField(max_length=32)
    fortiPassword = models.CharField(max_length=128)
    fortiDefaultGroupName = models.CharField(max_length=32)
    fortiAccessEnabledGroupName = models.CharField(max_length=32)
    fortiKeyStorePath = models.CharField(max_length=128,default="/etc/elkarforti/")

    def save(self, *args, **kwargs):
        data = self.fortiPassword.encode('utf8')

        keypath = self.fortiKeyStorePath+"/key.bin"
        if not(path.exists(keypath)):
            # Generate the key
            key = get_random_bytes(16)
            # Save the key to a file
            file_out = open(keypath, "wb") # wb = write bytes
            file_out.write(key)
            file_out.close()

        file_in =  open(keypath,"rb")
        key_from_file = file_in.read()
        file_in.close()
        cipher = AES.new(key_from_file, AES.MODE_CFB)
        ciphered_data = cipher.encrypt(data)
        encryptedpath = self.fortiKeyStorePath+"/encrypted.bin"
        file_out = open(encryptedpath, "wb")
        file_out.write(cipher.iv)
        file_out.write(ciphered_data)
        file_out.close()

        self.fortiPassword = 'encrypted'

        super().save(*args, **kwargs)  # Call the "real" save() method.

    @property
    def getEncrypted(self):
        configRecord = FortiParameters.objects.get(pk=1)
        fortiKeyStorePath = configRecord.fortiKeyStorePath
        keypath = fortiKeyStorePath+"/key.bin"
        encryptedpath = fortiKeyStorePath+"/encrypted.bin"
        file_in =  open(keypath,"rb")
        key_from_file = file_in.read()
        file_in.close()

        file_in =  open(encryptedpath,"rb")
        iv = file_in.read(16)
        ciphered_data = file_in.read()
        file_in.close()
        cipher = AES.new(key_from_file, AES.MODE_CFB, iv=iv)
        original_data = cipher.decrypt(ciphered_data)
        original_data = original_data.decode('utf8')
        # print('------------ ORIGINAL PASS -----------------')
        # print(original_data)
        return original_data



class FortiGroup(models.Model):
    name = models.CharField(max_length=200)
    enabled = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('index.html', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):

        parameters = FortiParameters.objects.get(id=1)
        device = pyfortiapi.FortiGate(ipaddr=parameters.fortiIP, username=parameters.fortiUserName, password= parameters.getEncrypted, port=parameters.fortiPort, vdom=parameters.fortiVdom)

        my_group   = device.get_address_group(self.name)
        my_address = device.get_firewall_address(self.name)

        if ((my_group == 404) and (my_address == 404)):
            raise ValidationError("The group name does not exists on Forti")


        super().save(*args, **kwargs)  # Call the "real" save() method.

        all_enabled_groups = FortiGroup.objects.filter(enabled=True)
        defaultGroupName = parameters.fortiDefaultGroupName  # Talde huts bat ez du Fortik onartzen
        payload_list=[]
        dict_gela = {'name':defaultGroupName}
        payload_list.append(dict_gela)

        for group in all_enabled_groups:
            dict_gela = {'name':group.name}
            payload_list.append(dict_gela)
            # print("payload_list: ", payload_list)

        payload = "{{'member': {} }}".format(payload_list)
        device.update_address_group(parameters.fortiAccessEnabledGroupName, payload)

    def __str__(self):
           return self.name



class FortiGroupForm(ModelForm):
    class Meta:
        model = FortiGroup
        fields = ['name', 'enabled']

elkarforti/groupaccess/forms.py
from django import forms

from .models import FortiGroup, FortiParameters
from django.contrib import admin

class FortiGroupForm(forms.ModelForm):
    class Meta:
        model = FortiGroup
        fields = ['enabled']

class FortiParametersAdminForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FortiParametersAdminForm, self).__init__(*args, **kwargs)
        self.fields['fortiPassword'].widget = forms.PasswordInput()

elkarforti/groupaccess/views.py
#from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.urls import reverse_lazy
from django.views import generic

from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView

from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
from .models import FortiGroup

from django.http import HttpResponse

#@login_required
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'groupaccess/index.html'
    context_object_name = 'group_list'

    def get_queryset(self):
        """Return the group list order by name."""
        return FortiGroup.objects.order_by('name')


class DetailView(generic.DetailView):
    model = FortiGroup
    template_name = 'groupaccess/detail.html'

class FortiGroupList(ListView):
    model = FortiGroup


class FortiGroupCreate(CreateView):
    model = FortiGroup
    fields = ['name','enabled']

class FortiGroupUpdate(LoginRequiredMixin, UpdateView):
    model = FortiGroup
    fields = ['enabled']
    success_url = reverse_lazy('groupaccess:index')

class FortiGroupDelete(DeleteView):
    model = FortiGroup
    success_url = reverse_lazy('fortigroup-list')

elkarforti/groupaccess/templates/groupaccess/base.html
{% load static %}
<html>
    <head>
        <title>Internet Atzipen kontrola</title>
        <link rel="stylesheet" href="{% static 'groupaccess/css/bootstrap.css' %}">

<div class="float-right">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
   {% endif %}
</div>

    </head>
    <body>
    <div class="page-header">
        <h1><img src="{% static "groupaccess/images/logo.png" %}" alt="Logo" /></h1>
        <h1>Internet Atzipen kontrola</h1>
  </ul>
    </div>
    <div class="content container">
        <div>
            <div>
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
    </body>
</html>

elkarforti/groupaccess/templates/groupaccess/fortigroup_form.html
{% extends 'groupaccess/base.html'%}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock %}

elkarforti/groupaccess/templates/groupaccess/index.html
{% extends 'groupaccess/base.html'%}

{% block content %}
{% if group_list %}
    <div class="float-left">
    <ul>
 
   {% for group in group_list %}
        {% if group.enabled %}
           <li> {% load static %} <img src="{% static "groupaccess/images/icon-yes.svg" %}" alt="Enabled!" /> <a href="{% url 'groupaccess:fortigroup_update' group.id %}">{{ group.name }}</a></li>
        {% else %}
           <li> {% load static %} <img src="{% static "groupaccess/images/icon-no.svg"  %}" alt="Enabled!" /> <a href="{% url 'groupaccess:fortigroup_update' group.id %}">{{ group.name }}</a></li>
        {% endif %}
 

        {% if forloop.counter|divisibleby:4 %}
            </ul>
            </div>
            <div class="float-left">
            <ul>
        {% endif %}

    {% endfor %}
    </ul>
    </div>

{% else %}
    <p>No groups are available.</p>
{% endif %}

{% endblock %}